### ISSUE TITLE
Listing your package on Pulsar

### ISSUE THREAD

**Issue by confused-Techie** [Trigan2025/oblivion-contrast-syntax#1]
Hello, this is confused-Techie from the Pulsar Team.

[Pulsar](https://github.com/pulsar-edit/pulsar) is an actively developed fork of Atom and one of our major efforts is to preserve the ecosystem of [Community Packages](https://web.pulsar-edit.dev/) that were previously published on Atom.io

While we want to list every single package that existed on Atom's Package Repository, we wanted to respect the license of each package within and ensure to only list packages that either the author has agreed for us to or packages that have a license that specify that redistribution is okay.

That is exactly why we are contacting you today, it seems your package `oblivion-contrast-syntax` has a license that makes it hard for us to determine if we should be listing it for redistribution.

All that needs to happen for you as a package maintainer is for you to give authorization for us to list your package. Just reply to this issue either way and we will respect your wishes.

Otherwise within 3 weeks, if there is no response, we will assume the answer is no and remove your package from the Pulsar Package Registry.

And if you've missed the deadline we have and still want your package to be published, feel free to [republish to Pulsar](https://pulsar-edit.dev/docs/launch-manual/sections/core-hacking/#publishing).

Thanks a ton for your time, hope you have a great day!

**Comment by Trigan2025** [comment]
Hello confused-Techie, sorry for the late answer.
My package states that the color scheme is based on the Oblivion color scheme of GtkSourceView, that is distributed under the GNU Lesser General Public License <http://www.gnu.org/licenses/>.
By Copyright None I only mean that there are no claims on my side. But although the final style slightly differs, I think that the underlying license continues to apply as if it was a [code translation](https://www.gnu.org/licenses/gpl-faq.html#TranslateCode).
Anyway, I'm not an expert on licenses, but I think it's safe to say that you can use it freely.

**Comment by confused-Techie** [comment]
As you are the author of this package, and you being alright with redistribution, and the underlying work is based on work with a GNU license then we are good to go. 

Thanks so much for your response! We will ensure to keep you package listed on the Pulsar Package Registry!
